apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
spec:
  template:
    spec:
      # Allow the container to see host processes
      hostPID: true
      containers:
        - name: kube-bench
          image: aquasec/kube-bench:latest
          # Use the appropriate benchmark profile; change 'eks-1.0.1' if needed
          command: ["kube-bench", "--benchmark", "cis-1.5"]
          # Optionally add privileged mode if you encounter permission issues:
          # securityContext:
          #   privileged: true
          volumeMounts:
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: etc-systemd
              mountPath: /etc/systemd
              readOnly: true
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"

