apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-config
          defaultMode: 420
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  index.html: |
    <html>
      <head><title>Welcome to Nginx</title></head>
      <body><h1>Hello, this is a monitored Nginx instance!</h1></body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: api-tls-secret
  namespace: nginx
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdDakNDQlBLZ0F3SUJBZ0lVWk9sOTc3UCsvOEtvUlBVQWdiOGFreGZoYVpNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daY3hDekFKQmdOVkJBWVRBa0ZWTVF3d0NnWURWUVFJREFOT1UxY3hEekFOQmdOVkJBY01CbE41Wkc1bAplVEVPTUF3R0ExVUVDZ3dGUVhoM1lYa3hIakFjQmdOVkJBc01GWEJ5YjJabGMzTnBiMjVoYkNCelpYSjJhV05sCmN6RVlNQllHQTFVRUF3d1BZWEJwTG1WNFlXMXdiR1V1WTI5dE1SOHdIUVlKS29aSWh2Y05BUWtCRmhCaGJXbHkKZW1GQVlYaDNZWGt1WTI5dE1CNFhEVEl5TURjeE56QXpOVFUxTVZvWERUTXlNRGN4TkRBek5UVTFNVm93Z1pjeApDekFKQmdOVkJBWVRBa0ZWTVF3d0NnWURWUVFJREFOT1UxY3hEekFOQmdOVkJBY01CbE41Wkc1bGVURU9NQXdHCkExVUVDZ3dGUVhoM1lYa3hIakFjQmdOVkJBc01GWEJ5YjJabGMzTnBiMjVoYkNCelpYSjJhV05sY3pFWU1CWUcKQTFVRUF3d1BZWEJwTG1WNFlXMXdiR1V1WTI5dE1SOHdIUVlKS29aSWh2Y05BUWtCRmhCaGJXbHllbUZBWVhoMwpZWGt1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdWJKOXVlemdRTWtNCjBDSk94K3BwNDhUbmRZZkZzSndOV243blJLb0RzMUs2SE02Z3BYZitTS2ZkWG9zZEpuUXNlaEF3TVJBbklrOEIKVWRsTXBhTGd1NUVqZ2M2MHF4eU9RQm5UTUR5M00wdFlGTE11OEhtbC85ZmpkNmZWd2hPMGR5NGdBZXoxQVJyNAo1Z2xtWDF4dGQycUl3MXVkenE5dXFuaGlxdmZFR1BKQlZ1MDFJa1B6V0JCUldoaUNGR3ovMjN5VitSSXhVOXhDCnZZNkt3bXJlTWo2bUd0L3orZ0VYZjFhZEVjWlZabWpNK0EvRTF6YS8wQ3dTR2ZhY21va0FZbTRPaWRWVk1mbW8KbGNQRW0rUEw2QVpyMFpWUm1uRjN4S3crT3YrVEtFTGtlV2hFTDdtc1l0ZHQwSTVLQXBPaHlZYUZ3ZStHQy9HSApXWnZqRFB2SWZ3SURBUUFCbzRJQ1NqQ0NBa1l3SFFZRFZSME9CQllFRkFNRytWeXJTRExaV2xOMWEwTnFNVnpHCit6Z0lNSUhYQmdOVkhTTUVnYzh3Z2N5QUZBTUcrVnlyU0RMWldsTjFhME5xTVZ6Ryt6Z0lvWUdkcElHYU1JR1gKTVFzd0NRWURWUVFHRXdKQlZURU1NQW9HQTFVRUNBd0RUbE5YTVE4d0RRWURWUVFIREFaVGVXUnVaWGt4RGpBTQpCZ05WQkFvTUJVRjRkMkY1TVI0d0hBWURWUVFMREJWd2NtOW1aWE56YVc5dVlXd2djMlZ5ZG1salpYTXhHREFXCkJnTlZCQU1NRDJGd2FTNWxlR0Z0Y0d4bExtTnZiVEVmTUIwR0NTcUdTSWIzRFFFSkFSWVFZVzFwY25waFFHRjQKZDJGNUxtTnZiWUlVWk9sOTc3UCsvOEtvUlBVQWdiOGFreGZoYVpNd0RBWURWUjBUQkFVd0F3RUIvekFMQmdOVgpIUThFQkFNQ0F2d3dnWllHQTFVZEVRU0JqakNCaTRJTFpYaGhiWEJzWlM1amIyMkNEU291WlhoaGJYQnNaUzVqCmIyMkNFVzVuYVc1NExtVjRZVzF3YkdVdVkyOXRnZzloYm0wdVpYaGhiWEJzWlM1amIyMkNFR0Z3YVcwdVpYaGgKYlhCc1pTNWpiMjJDRTNSeVlXWm1hV011WlhoaGJYQnNaUzVqYjIyQ0QyRndhUzVsZUdGdGNHeGxMbU52YllJUgpiMkYxZEdndVpYaGhiWEJzWlM1amIyMHdnWllHQTFVZEVnU0JqakNCaTRJTFpYaGhiWEJzWlM1amIyMkNEU291ClpYaGhiWEJzWlM1amIyMkNFVzVuYVc1NExtVjRZVzF3YkdVdVkyOXRnZzloYm0wdVpYaGhiWEJzWlM1amIyMkMKRUdGd2FXMHVaWGhoYlhCc1pTNWpiMjJDRTNSeVlXWm1hV011WlhoaGJYQnNaUzVqYjIyQ0QyRndhUzVsZUdGdApjR3hsTG1OdmJZSVJiMkYxZEdndVpYaGhiWEJzWlM1amIyMHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ25uCkVVSHZZMXVReldacnpwSGRSUnJqNWI0MDZkUTFzYWttV3dPeEl1aXBvZlU2aGQxSGdiZTlRZnd3TWNuMEdyVEsKRE5STnF0enNGRVZxOWZ3MUFDd3ZOT2dkeXRUTEp5MVU3ZG1CWFA4T2E2dzlWOC9oRTNOMjdCLzcyZzFTMmx6QQpoSmtvaFhJem5sK1E2aDlRL3FtUGdudEdOL3RqL0RrOHVpNmRwb1c3cElZQ0diV2JuMkd4SGFQdnk4TVFGbjNsCnZjTkt2K1NZZkJpUmtBMTNOUVJWUHpKdlplWTdGTDV4WXgzQlNkaWh5YTdwZzUvR21BL3RMV0psUG81MGQwRkkKeXh3UXdaaFFHY1N0YUE4bTMwb0NnYisyM0ZsWlRKZDZ6SW8zUmxmNUp3b2NBOTJqbFFaWGZXYkNVWkF1MnVjUwpqTVZZK2R4RWkvcloxeTZibW0wPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdWJKOXVlemdRTWtNMENKT3grcHA0OFRuZFlmRnNKd05XbjduUktvRHMxSzZITTZnCnBYZitTS2ZkWG9zZEpuUXNlaEF3TVJBbklrOEJVZGxNcGFMZ3U1RWpnYzYwcXh5T1FCblRNRHkzTTB0WUZMTXUKOEhtbC85ZmpkNmZWd2hPMGR5NGdBZXoxQVJyNDVnbG1YMXh0ZDJxSXcxdWR6cTl1cW5oaXF2ZkVHUEpCVnUwMQpJa1B6V0JCUldoaUNGR3ovMjN5VitSSXhVOXhDdlk2S3dtcmVNajZtR3QveitnRVhmMWFkRWNaVlptak0rQS9FCjF6YS8wQ3dTR2ZhY21va0FZbTRPaWRWVk1mbW9sY1BFbStQTDZBWnIwWlZSbW5GM3hLdytPditUS0VMa2VXaEUKTDdtc1l0ZHQwSTVLQXBPaHlZYUZ3ZStHQy9HSFdadmpEUHZJZndJREFRQUJBb0lCQUhnWUIxZUc2a0Q3eFYyVgowbjFZRE1OUlJKK3QveHdJMEZvR1dHci95UVRnSzUwVnhLOCt1eVVoNnZpSjM0QlBBYlN2WTN0WGh2ZVpRTEUrCloyTjN3ditMRGZ1VlF5S21oUmpQbXRWSGJ2T3RkbmxzcUo2OURhNDRZTk94cDN5c1libnlDcUUwTGY5WkFqOUQKTlFIWE5MUldJYnkyTTRqSHpEcFRRUHh3NEZHQXYvSTNhRTl5VlhZZ1pTWWlvSFpiWkRJY0UyQnRTZWs2cjZxZwowZHFXRlNONGZzUldLczJqUFM2ZjdPejRMclZML2tzTXkraDd1MHJQbU1sVGpUN2pkNHNORGZkTHdPb09YZ29BCmVIMllaMzVNZnc5MGdQeTF2bjRnOGp6V0FTeDBHWDRnNnBKaHFtVDhCQnV6NmhHWktrdzIwcG1DbjQxWjUvMlUKT2VDY01ZRUNnWUVBN0ZUVENsc2R4Tysweis4UGRuZUVyYXA5ZmNhdTNMdEdOUVZremNleVdYMVd5WUZ6MDZLcQphOCtsaFhBaFhmNCs5T2J6NHFyNitoTk9SRDc0ZndXcHBxcmNPVE9teXBqMTg3MmZ2bGVpa1Q2c0Z1TGFDRmxWCk1zMlZWSUt3TnpOVkY4TUlSc2hONzBaTGlpQ3RRdS9yOVVBSmpHdzNQb2JoOWNqT1lST3JuV3NDZ1lFQXlTYmcKc3YvUUM1RHBOV3RmKzFLMmZOTW9PdWxyclB1RW1zZ3p6MTVuMDFCcUJjbUU5OU52dTFTc2s3eDZ3c0RRaHRpegpYNVIyVUVmRThpTmw5dEJtQnpIOExnYXZVREVoYkRlSW5LYUlVMXhuTTJ3KzZGRWNyMWU3cnErb3czR1FIbzJnClpYY3lLUjE1WUU1cXpUK3JkNzB2RnM3Z0NsaStFWkdaUnVYQlVqMENnWUFRRFBiRVZrbmdUVE5uaCtIeDlzNFIKQ1dvNmQ1cjZyTkZvMm5QdE1lbmdBQTQ3NDBuZGpzZXFTTkVDRGdxR0dyVmw1cVdidUdjUlF1eG00Q3Y2WElVWQpKN1NMUWdISzhyYUpsbEJhR2hPVmI3ODZVcS9pTDBjRkMwZGdGUHdvMDVpczQzY1ZiNWN6Yi8vRFl0TEJvQS9UCmVVVHN2NURFODE0M1Zpc0dGdExwL3dLQmdRREJxbmJJb0ZjejY0ODg2V1o5Mk1MdUozY2lVVDVrUzd6K01TY0EKem9uMEFBWTBFRE8vVDRqUnVkSjJZdzltbHJHdVF0RmdndFh1c1VyRFBxV2JIa1k5UXpqakwzaDNJdlprOUlySgpGK1ZGTFVBSFdINnd1ZmQrTWwvMjdoVDBKMUIwdWpMbHZmOURhcWREdS94RUpMcjRDK05jZUUxb2FNeUdxY0lECmFvM1ltUUtCZ0hQT2Rta3RLTDhYLzN4VG1xRHAyMld2S0pZMjY1RVV3K3VRdkQ4d214eGtSM2lWTVFVWEgyQncKWTgrTHc5KzNJWkJXcmFMUjExd0JKK1R6K1RjZkk5eGExd0lVNDRMZmtmcmNjWnNsTEhWUTJRanRyOUVKZHR4Sgo3N1NYaFBXZHpwY0JNNExTWTY5Ty8xL3V6dUhQYm9iZlp5RTgySG41M3FoZVhpM0hzTllSCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: devsecops-tls
  namespace: nginx
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoRENDQXd1Z0F3SUJBZ0lTQTZLMDVjbnpVcTBzSGpwdS83aXdvcHNVTUFvR0NDcUdTTTQ5QkFNRE1ESXgKQ3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MU1aWFFuY3lCRmJtTnllWEIwTVFzd0NRWURWUVFERXdKRgpOakFlRncweU5UQXlNalV5TVRVMU1ERmFGdzB5TlRBMU1qWXlNVFUxTURCYU1CMHhHekFaQmdOVkJBTU1FaW91ClpHVjJjMlZqYjNCekxtNWxkQzVoZFRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkxialUvM08KcEhwTkR2ckhZeDlwcHFNUDFLOXNRQjFrUGdpRGhoV2VRUGV0ZjFMbk82VXZPT1JvY0N0eVFUREtMYm9lSjN6TgorYXRSSUE5S0lTS1dmR2VqZ2dJVU1JSUNFREFPQmdOVkhROEJBZjhFQkFNQ0I0QXdIUVlEVlIwbEJCWXdGQVlJCkt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkNIRUF2Uk8KWFJrMXpWbGdMeURkMmJKZWdINGZNQjhHQTFVZEl3UVlNQmFBRkpNblJwZ0RxVkZvanBqV3hFSkkyeU8vV0pUUwpNRlVHQ0NzR0FRVUZCd0VCQkVrd1J6QWhCZ2dyQmdFRkJRY3dBWVlWYUhSMGNEb3ZMMlUyTG04dWJHVnVZM0l1CmIzSm5NQ0lHQ0NzR0FRVUZCekFDaGhab2RIUndPaTh2WlRZdWFTNXNaVzVqY2k1dmNtY3ZNQjBHQTFVZEVRUVcKTUJTQ0Vpb3VaR1YyYzJWamIzQnpMbTVsZEM1aGRUQVRCZ05WSFNBRUREQUtNQWdHQm1lQkRBRUNBVENDQVFRRwpDaXNHQVFRQjFua0NCQUlFZ2ZVRWdmSUE4QUIxQU42RmdkZFFKSHhyemN1dlZqZkY1NEhHVE9SdTFoZGpuNDgwCnB5Yko0cjAzQUFBQmxUOVF2eW9BQUFRREFFWXdSQUlnVUpDNStQWXNpVDFLR0FYZXo2NG5DdTl6eHQwR0FUUmgKclp5VTcxdTEvMk1DSURJQnVibk1YYkRzWU1sTHRTTFhYWGJIRUx3ekdjT3hiOFkyUEY3K0dJaVhBSGNBenhGVwo3dFV1ZksvemgxdlphUzZiNlJweFowcXdGK3lzQWRKYmQ4N01Pd2dBQUFHVlAxQy9iZ0FBQkFNQVNEQkdBaUVBCm5JU3N5TVI2RmdpNGFTVHdCcSsyR3pmekNxSDNuTXRUTUZrM0dzOVRHQ0FDSVFEQ0JHYWpuODEvSUxkMVUxengKSW9Sa3BuaHFSU0Fsbm5SbHF6TWtzTzlaVlRBS0JnZ3Foa2pPUFFRREF3Tm5BREJrQWpCL2gzL29rZzBqZ0VEcgpTZ0dQSkVhdDRPYjdIWGlBbmpmK25Bay84aU8zeDY1RGdzL0xNY3MwcWoycEJEZXBHVTBDTUYxZlFuN1BSbzlhClBYRlFab3lWSkxtYkFzdnZXWXhKa2JJWHVlZ21UUEgwY3UwRitWWU5LN3dKK1oybmNTT2tKQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVWekNDQWorZ0F3SUJBZ0lSQUxCWFBwRnpseWR3MjdTSHl6cEZLemd3RFFZSktvWklodmNOQVFFTEJRQXcKVHpFTE1Ba0dBMVVFQmhNQ1ZWTXhLVEFuQmdOVkJBb1RJRWx1ZEdWeWJtVjBJRk5sWTNWeWFYUjVJRkpsYzJWaApjbU5vSUVkeWIzVndNUlV3RXdZRFZRUURFd3hKVTFKSElGSnZiM1FnV0RFd0hoY05NalF3TXpFek1EQXdNREF3CldoY05NamN3TXpFeU1qTTFPVFU1V2pBeU1Rc3dDUVlEVlFRR0V3SlZVekVXTUJRR0ExVUVDaE1OVEdWMEozTWcKUlc1amNubHdkREVMTUFrR0ExVUVBeE1DUlRZd2RqQVFCZ2NxaGtqT1BRSUJCZ1VyZ1FRQUlnTmlBQVRaOFo1RwpoL2doY1dDb0p1dWorcm5xMmgyNUVxZlVKdGxSRkxGaGZIV1d2eUlMT1IvVnZ0RUtScW90UEVvSmhDNitRSlZWCjZSbEFOMloxN1RKT2R3UkorSEI3d3hqbnp2ZHhFUDZzZE5nQTFPMXRISE1XTXhDY09yTHFiR0wwdmJpamdmZ3cKZ2ZVd0RnWURWUjBQQVFIL0JBUURBZ0dHTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApBVEFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwR0ExVWREZ1FXQkJTVEowYVlBNmxSYUk2WTFzUkNTTnNqCnYxaVUwakFmQmdOVkhTTUVHREFXZ0JSNXRGbm1lN2JsNUFGemdBaUl5QnBZOXVtYmJqQXlCZ2dyQmdFRkJRY0IKQVFRbU1DUXdJZ1lJS3dZQkJRVUhNQUtHRm1oMGRIQTZMeTk0TVM1cExteGxibU55TG05eVp5OHdFd1lEVlIwZwpCQXd3Q2pBSUJnWm5nUXdCQWdFd0p3WURWUjBmQkNBd0hqQWNvQnFnR0lZV2FIUjBjRG92TDNneExtTXViR1Z1ClkzSXViM0puTHpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWZZdDdTaUExc2dXR0NJcHVuazQ2cjRBRXhJUmMKTXhrS2dVaE5scnJ2MUIyMWhPYVhOLzVtaUUrTE9UYnJjbVUvTTl5dkM2TVZZNzMwR05Gb0w4SWhKOGo4dnJPTApwTVkyMk9QNmJhUzFrOVlNcnREVGx3SkhvR2J5MDRUaFRVZUJEa3NTOVJpdUh2aWNacUJlZFFkSUY2NXBadWhwCmVEY0dCY0xpWWFzUXIvRU81Z3h4dEx5VG1nc0hTT1ZTQmNGT245bGd2N0xFQ1BxOWk3bWZIM21weGdyUktTeEgKcE9vWjBLWE1jQitoSHV2bGtsSG50dmNJMG1NTVEwbWhZajZxdE1GU3RrRjFScENHM0lQZEl3cFZDUXF1OEdWNwpzOHVia25SenMrM0MvQm0xOVJGT29pUHBEa3d2eU5mdm1RMTRYa3lxcUtLNW9aOHpoRDMya0ZSUWt4YTh1WlN1Cmg0YVRJbUZ4a251Mzl3YUJ4SVJYRTRqS3hsQW1RYzRRakZab3ExS21RcVFnMEovMUpGOFJsRnZKYXMxVmNqTHYKWWx2VUIydDZucE82b1FqQjNsK1BOZjBEcFFIN2lVeDNXejVBalFDaTZMMjVGanlFMDZxNkJaL1FsbXRZZGwvOApaWWFvNFNScVBFcy82Y0FpRitRZjV6ZzJVa2FXdERwaGwxTEtNdVROTG90dnNYOTlIUDY5VjJmYU55ZWdvZFEwCkx5VEFwci92VDAxWVBFNDZ2TnNETGdLKzRjTDZUcnpDL2E0V2NtRjVTUko5Mzh6cnYvZHVKSExYUUlrdTV2MCsKRXdPeTU5SGRtMFBUL0VyLzg0ZERWMENTamRSLzJYdVpNM2tweXNTS0xnRDFjS2lEQStJUmd1T0RDeGZPOWN5WQpJZzQ2djltRm1CdnlIMDQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2VrNGh6NDNvWTQzK3ZIN2cKZUoycTBxN09kRmw5cGJVazh4WlZCMXk3bkVpaFJBTkNBQVMyNDFQOXpxUjZUUTc2eDJNZmFhYWpEOVN2YkVBZApaRDRJZzRZVm5rRDNyWDlTNXp1bEx6amthSEFyY2tFd3lpMjZIaWQ4emZtclVTQVBTaUVpbG54bgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nginx-ingress
  namespace: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: test.nginx.192.168.210.201.nip.io
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - test.nginx.192.168.210.201.nip.io
    secretName: api-tls-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-cilium-ingress
  namespace: nginx
spec:
  ingressClassName: cilium
  rules:
  - host: test.cilium.192.168.210.202.nip.io
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - test.cilium.192.168.210.202.nip.io
    secretName: api-tls-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecops-ingress
  namespace: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: nginx.devsecops.net.au
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - nginx.devsecops.net.au
    secretName: devsecops-tls
