# backup-target.yaml
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  # bucket@region/path
  backupTargetURL: "s3://longhorn-backups@us-east-1/"
  credentialSecret: "minio-longhorn-secret"
  pollInterval: 5m0s
