apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn-system
data:
  default-resource.yaml: |-
    backup-target:                    "s3://longhorn?endpoint=minio.minio.svc.cluster.local:9000&ssl=false"
    backup-target-credential-secret:  "longhorn-minio-secret"
    backupstore-poll-interval:        "300"

