apiVersion: v1
kind: Secret
metadata:
  name: longhorn-minio-credentials
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ZGVtbzEyMzQ1
  AWS_SECRET_ACCESS_KEY: ZGVtbzEyMzQ1
  AWS_ENDPOINTS: aHR0cDovL21pbmlvLm1pbmlvLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDAv